### ISSUE TITLE
Needs Update

### ISSUE THREAD

**Issue by logixworx** [gschup/ggrs_demo#1]
This example appears to be out of date - can you update this to build witth current version of Matchbox?  Thanks

**Comment by gschup** [comment]
I updated to matchbox 0.5 two months ago, which in my understanding is the most recently released version of matchbox.

**Comment by logixworx** [comment]
> I updated to matchbox 0.5 two months ago, which in my understanding is the most recently released version of matchbox.

was it tested on the 0.5 matchbox server? I got an error that seems protocol related.. I'll get more details later.

**Comment by gschup** [comment]
closed due to inactivity
